# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar_produto.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_produto(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(655, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(655, 473))
        Form.setMaximumSize(QtCore.QSize(655, 473))
        Form.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 221, 21))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(540, 10, 101, 71))
        self.label.setStyleSheet("image: url(:/img/img/icons8-caixa.svg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(450, 430, 191, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.cadastrar = QtWidgets.QPushButton(self.splitter)
        self.cadastrar.setStyleSheet("image: url(:/img/img/icons8-ok-filled.svg);\n"
"background-color:   rgb(200,200,200);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icons8-ok-filled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastrar.setIcon(icon)
        self.cadastrar.setObjectName("cadastrar")
        self.cancelar = QtWidgets.QPushButton(self.splitter)
        self.cancelar.setStyleSheet("background-color:   rgb(200,200,200);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/icons8-cancelar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelar.setIcon(icon1)
        self.cancelar.setObjectName("cancelar")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 658, 41))
        self.label_6.setStyleSheet("background-color:  rgba(255, 207, 183, 200);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 631, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 591, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_17 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_17.setGeometry(QtCore.QRect(10, 10, 541, 281))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_6.setContentsMargins(2, 4, 0, 9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget_17)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_18 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_18.setGeometry(QtCore.QRect(10, 30, 211, 95))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.codigo_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.codigo_4.setEnabled(True)
        self.codigo_4.setObjectName("codigo_4")
        self.horizontalLayout_10.addWidget(self.codigo_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.descricao_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.descricao_4.setEnabled(True)
        self.descricao_4.setObjectName("descricao_4")
        self.horizontalLayout_11.addWidget(self.descricao_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.garantia_4 = QtWidgets.QSpinBox(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.garantia_4.setFont(font)
        self.garantia_4.setMinimum(1)
        self.garantia_4.setObjectName("garantia_4")
        self.horizontalLayout_12.addWidget(self.garantia_4)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_19.setGeometry(QtCore.QRect(300, 60, 228, 63))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_13.addWidget(self.label_30)
        self.fornecedor_4 = QtWidgets.QComboBox(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fornecedor_4.setFont(font)
        self.fornecedor_4.setStyleSheet("background-color:  rgb(200,200,200);")
        self.fornecedor_4.setObjectName("fornecedor_4")
        self.horizontalLayout_13.addWidget(self.fornecedor_4)
        self.adicionar_4 = QtWidgets.QPushButton(self.layoutWidget_19)
        self.adicionar_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/icons8-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adicionar_4.setIcon(icon2)
        self.adicionar_4.setObjectName("adicionar_4")
        self.horizontalLayout_13.addWidget(self.adicionar_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_14.addWidget(self.label_31)
        self.data_entrada_4 = QtWidgets.QDateEdit(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.data_entrada_4.setFont(font)
        self.data_entrada_4.setObjectName("data_entrada_4")
        self.horizontalLayout_14.addWidget(self.data_entrada_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.layoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_20 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_20.setGeometry(QtCore.QRect(10, 20, 511, 80))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_20)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.infraestrutura_4 = QtWidgets.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.infraestrutura_4.setFont(font)
        self.infraestrutura_4.setObjectName("infraestrutura_4")
        self.gridLayout_9.addWidget(self.infraestrutura_4, 1, 2, 1, 2)
        self.outros_4 = QtWidgets.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.outros_4.setFont(font)
        self.outros_4.setObjectName("outros_4")
        self.gridLayout_9.addWidget(self.outros_4, 0, 3, 1, 1)
        self.vigilancia_4 = QtWidgets.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.vigilancia_4.setFont(font)
        self.vigilancia_4.setObjectName("vigilancia_4")
        self.gridLayout_9.addWidget(self.vigilancia_4, 1, 0, 1, 1)
        self.informatica_4 = QtWidgets.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.informatica_4.setFont(font)
        self.informatica_4.setObjectName("informatica_4")
        self.gridLayout_9.addWidget(self.informatica_4, 0, 2, 1, 1)
        self.escritorio_4 = QtWidgets.QCheckBox(self.layoutWidget_20)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.escritorio_4.setFont(font)
        self.escritorio_4.setObjectName("escritorio_4")
        self.gridLayout_9.addWidget(self.escritorio_4, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.splitter.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cadastrar, self.cancelar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cadastrar Produto"))
        self.label_3.setText(_translate("Form", "Cadastrar Produto"))
        self.cadastrar.setText(_translate("Form", "Cadastrar"))
        self.cancelar.setText(_translate("Form", "Cancelar"))
        self.groupBox_2.setTitle(_translate("Form", "Caracteristicas"))
        self.label_26.setText(_translate("Form", "Codigo"))
        self.label_27.setText(_translate("Form", "Descrição"))
        self.label_28.setText(_translate("Form", "Garantia"))
        self.label_29.setText(_translate("Form", "Meses"))
        self.label_30.setText(_translate("Form", "Forncedor"))
        self.label_31.setText(_translate("Form", "Data Entrada"))
        self.groupBox_9.setTitle(_translate("Form", "Tipo"))
        self.infraestrutura_4.setText(_translate("Form", "Infra Estrutura"))
        self.outros_4.setText(_translate("Form", "Outros"))
        self.vigilancia_4.setText(_translate("Form", "Vigilancia"))
        self.informatica_4.setText(_translate("Form", "Informática"))
        self.escritorio_4.setText(_translate("Form", "Escritório"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Produto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Observações"))

import recursos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_produto()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

