# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consulta_produto.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_consultaProduto(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(808, 540)
        Form.setMinimumSize(QtCore.QSize(808, 540))
        Form.setMaximumSize(QtCore.QSize(808, 540))
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 811, 41))
        self.label_6.setStyleSheet("background-color:  rgba(255, 207, 183, 200);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 221, 21))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(720, 10, 81, 71))
        self.label.setStyleSheet("image: url(:/img/img/icons8-view-80.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 791, 251))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 35, 561, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.informatica = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.informatica.setFont(font)
        self.informatica.setObjectName("informatica")
        self.gridLayout_4.addWidget(self.informatica, 0, 1, 1, 1)
        self.outros = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outros.setFont(font)
        self.outros.setObjectName("outros")
        self.gridLayout_4.addWidget(self.outros, 0, 2, 1, 1)
        self.vigilancia = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.vigilancia.setFont(font)
        self.vigilancia.setObjectName("vigilancia")
        self.gridLayout_4.addWidget(self.vigilancia, 1, 0, 1, 1)
        self.infraestrutura = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.infraestrutura.setFont(font)
        self.infraestrutura.setObjectName("infraestrutura")
        self.gridLayout_4.addWidget(self.infraestrutura, 1, 1, 1, 2)
        self.escritorio = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.escritorio.setFont(font)
        self.escritorio.setObjectName("escritorio")
        self.gridLayout_4.addWidget(self.escritorio, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 50, 337, 23))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setGeometry(QtCore.QRect(10, 80, 337, 23))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(690, 80, 89, 78))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.consultar = QtWidgets.QPushButton(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icons8-search-filled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consultar.setIcon(icon)
        self.consultar.setObjectName("consultar")
        self.cadastrar = QtWidgets.QPushButton(self.splitter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/icons8-product-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastrar.setIcon(icon1)
        self.cadastrar.setObjectName("cadastrar")
        self.cancelar = QtWidgets.QPushButton(self.splitter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/icons8-cancelar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelar.setIcon(icon2)
        self.cancelar.setObjectName("cancelar")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 661, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_18 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_18.setGeometry(QtCore.QRect(10, 30, 211, 95))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.codigo_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.codigo_4.setEnabled(True)
        self.codigo_4.setObjectName("codigo_4")
        self.horizontalLayout_10.addWidget(self.codigo_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.descricao_4 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.descricao_4.setEnabled(True)
        self.descricao_4.setObjectName("descricao_4")
        self.horizontalLayout_11.addWidget(self.descricao_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.garantia_4 = QtWidgets.QSpinBox(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.garantia_4.setFont(font)
        self.garantia_4.setMinimum(1)
        self.garantia_4.setObjectName("garantia_4")
        self.horizontalLayout_12.addWidget(self.garantia_4)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_18)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_19.setGeometry(QtCore.QRect(300, 60, 228, 63))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_13.addWidget(self.label_30)
        self.fornecedor_4 = QtWidgets.QComboBox(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fornecedor_4.setFont(font)
        self.fornecedor_4.setStyleSheet("background-color:  rgb(200,200,200);")
        self.fornecedor_4.setObjectName("fornecedor_4")
        self.horizontalLayout_13.addWidget(self.fornecedor_4)
        self.adicionar_4 = QtWidgets.QPushButton(self.layoutWidget_19)
        self.adicionar_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/icons8-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adicionar_4.setIcon(icon3)
        self.adicionar_4.setObjectName("adicionar_4")
        self.horizontalLayout_13.addWidget(self.adicionar_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_14.addWidget(self.label_31)
        self.data_entrada_4 = QtWidgets.QDateEdit(self.layoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.data_entrada_4.setFont(font)
        self.data_entrada_4.setObjectName("data_entrada_4")
        self.horizontalLayout_14.addWidget(self.data_entrada_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.groupBox_2.raise_()
        self.splitter_3.raise_()
        self.splitter_2.raise_()
        self.splitter.raise_()
        self.label_6.raise_()
        self.groupBox_3.raise_()
        self.tabela = QtWidgets.QTableWidget(Form)
        self.tabela.setGeometry(QtCore.QRect(10, 301, 791, 231))
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(0)
        self.tabela.setRowCount(0)
        self.label_6.raise_()
        self.label_3.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.tabela.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Consulta Produto"))
        self.label_3.setText(_translate("Form", "Consulta Produto"))
        self.groupBox_2.setTitle(_translate("Form", "Tipo"))
        self.informatica.setText(_translate("Form", "Informática"))
        self.outros.setText(_translate("Form", "Outros"))
        self.vigilancia.setText(_translate("Form", "Vigilancia"))
        self.infraestrutura.setText(_translate("Form", "Infra Estrutura"))
        self.escritorio.setText(_translate("Form", "Escritório"))
        self.consultar.setText(_translate("Form", "Consultar"))
        self.cadastrar.setText(_translate("Form", "Cadastrar"))
        self.cancelar.setText(_translate("Form", "Cancelar"))
        self.groupBox_3.setTitle(_translate("Form", "Caracteristicas"))
        self.label_26.setText(_translate("Form", "Codigo"))
        self.label_27.setText(_translate("Form", "Descrição"))
        self.label_28.setText(_translate("Form", "Garantia"))
        self.label_29.setText(_translate("Form", "Meses"))
        self.label_30.setText(_translate("Form", "Forncedor"))
        self.label_31.setText(_translate("Form", "Data Entrada"))

import recursos

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_consultaProduto()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

