# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consulta_fornecedor.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_consultaProduto(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(624, 539)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 221, 21))
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 811, 41))
        self.label_6.setStyleSheet("background-color:  rgba(255, 207, 183, 200);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(540, 0, 81, 71))
        self.label.setStyleSheet("image: url(:/img/img/icons8-view-80.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 50, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groupBox.setObjectName("groupBox")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setGeometry(QtCore.QRect(310, 190, 81, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(17, 30, 233, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.codigo = QtWidgets.QLineEdit(self.layoutWidget)
        self.codigo.setEnabled(True)
        self.codigo.setObjectName("codigo")
        self.horizontalLayout_2.addWidget(self.codigo)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 70, 226, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.nome = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nome.setObjectName("nome")
        self.horizontalLayout_3.addWidget(self.nome)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 50, 211, 111))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 137, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.otimo = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.otimo.setFont(font)
        self.otimo.setObjectName("otimo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.otimo)
        self.bom = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bom.setFont(font)
        self.bom.setObjectName("bom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bom)
        self.regular = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.regular.setFont(font)
        self.regular.setObjectName("regular")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.regular)
        self.ruim = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ruim.setFont(font)
        self.ruim.setObjectName("ruim")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ruim)
        self.consultar = QtWidgets.QPushButton(Form)
        self.consultar.setGeometry(QtCore.QRect(520, 85, 89, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/icons8-search-filled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.consultar.setIcon(icon)
        self.consultar.setObjectName("consultar")
        self.cancelar = QtWidgets.QPushButton(Form)
        self.cancelar.setGeometry(QtCore.QRect(520, 140, 89, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/icons8-cancelar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelar.setIcon(icon1)
        self.cancelar.setObjectName("cancelar")
        self.tabela = QtWidgets.QTableWidget(Form)
        self.tabela.setGeometry(QtCore.QRect(10, 170, 601, 341))
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(0)
        self.tabela.setRowCount(0)
        self.cadastrar = QtWidgets.QPushButton(Form)
        self.cadastrar.setGeometry(QtCore.QRect(520, 112, 89, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/icons8-product-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastrar.setIcon(icon2)
        self.cadastrar.setObjectName("cadastrar")
        self.label_6.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.consultar.raise_()
        self.cancelar.raise_()
        self.tabela.raise_()
        self.cadastrar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Consulta Fornecedor"))
        self.label_3.setText(_translate("Form", "Consulta Fornecedor"))
        self.groupBox.setTitle(_translate("Form", "Dados"))
        self.label_2.setText(_translate("Form", "Codigo"))
        self.label_4.setText(_translate("Form", "Nome"))
        self.groupBox_3.setTitle(_translate("Form", "Prioridade"))
        self.otimo.setText(_translate("Form", "Ótimo"))
        self.bom.setText(_translate("Form", "Bom"))
        self.regular.setText(_translate("Form", "Regular"))
        self.ruim.setText(_translate("Form", "Ruím"))
        self.consultar.setText(_translate("Form", "Consultar"))
        self.cancelar.setText(_translate("Form", "Cancelar"))
        self.cadastrar.setText(_translate("Form", "Cadastrar"))

import recursos 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_consultaProduto()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

